dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
    allow_failures:
        - python: "3.8-dev"

install: pip install tox-travis
script: tox
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
